### PR TITLE
Changes icons to ha-icons and fixes list.

### PR DESCRIPTION
**Pull request by QSonx**

### CODE REVIEW

**Comment by QSonx** [comment]
My bad. meant to do that into my fork first. Still working on it. But I did find it wasn't completely working on my most recent up to date installation of homeassistant.

**Comment by moralmunky** [comment]
Cool. Let me know what issues you are seeing. I’m on 111.3 and haven’t noticed anything other than the one issue I have already recorded.

**Comment by QSonx** [comment]
We are on the same version. But the iron-icons just weren't showing for me in either Android mobile or web. I was also working on css for the href as the non themed links would basically be hidden on a dark theme. I did however notice if I make a change to a resource file my mobile app caches it and requires me to clear the cache data for the mobile app to download the updated resource file and reflect my changes. Later today I will test my iPad and see if I have issues with the camera entity.

**Comment by moralmunky** [comment]
LOL, you are right. I didn't even noticed the icons being gone. Also, clearing the front end cache did allow the camera component to show. Thanks!

**Pull request closed without merging**
